import PageNotFound from './page-not-found/pageNotFound.vue'
import Login from './login/Login.vue'
import Hero from './hero/hero.vue'
import Crisis from './crisis/crisis'
import Admin from './admin/admin'
import Dashboard from './admin/children/dashboard'
import HeroManage from './admin/children/hero-manage'
import CrisisManage from './admin/children/crisis-manage'
import HeroDetailPage from './hero-detail/hero-detail-page'
import Compose from './compose/compose'
export { PageNotFound, Login, Hero, Crisis, Admin, Dashboard, HeroManage, CrisisManage, HeroDetailPage, Compose }
